version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing npm dependencies
      - npm ci
  build:
    commands:
      - echo compiling code
      - npm run build

artifacts:
  files:
    - dist/index.js
    - node_modules/**/*
    - package.json